# Generated by Django 5.2.6 on 2025-11-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('grade', models.IntegerField(help_text='e.g., 9, 10, 11, 12')),
                ('major', models.CharField(blank=True, help_text='e.g., Science, Arts, Commerce', max_length=100, null=True)),
            ],
        ),
    ]
